[editor]
bg = "#1e1e30"
fg = "#abb2bf"
select_bg = "#3a3a55"
inactive_select_bg = "#3a3a55"
caret = "#abb2bf"
caret_width = 1
border_width = 0
focus_border_width = 0

[general]
comment = "#4e577b"
error = "#ff5370"
escape = "#82aaff"
keyword = "#57c7ff"
name = "#82aaff"
string = "#f29e74"
punctuation = "#89ddff"

[keyword]
constant = "#ff79c6"
declaration = "#57c7ff"
namespace = "#57c7ff"
pseudo = "#57c7ff"
reserved = "#ff79c6"
type = "#ff79c6"

[name]
attr = "#82aaff"
builtin = "#ffcc66"
builtin_pseudo = "#ffcc66"
class = "#ffcc66"
class_variable = "#ffcc66"
constant = "#ffcc66"
decorator = "#ffcc66"
entity = "#ffcc66"
exception = "#ffcc66"
function = "#ffcc66"
global_variable = "#ffcc66"
instance_variable = "#ffcc66"
label = "#ffcc66"
magic_function = "#ffcc66"
magic_variable = "#ffcc66"
namespace = "#ffcc66"
tag = "#ffcc66"
variable = "#ffcc66"

[operator]
symbol = "#89ddff"
word = "#89ddff"

[string]
affix = "#c3e88d"
char = "#ecc48d"
delimeter = "#c3e88d"
doc = "#c3e88d"
double = "#c3e88d"
escape = "#c3e88d"
heredoc = "#c3e88d"
interpol = "#c3e88d"
regex = "#c3e88d"
single = "#c3e88d"
symbol = "#c3e88d"

[number]
binary = "#f7768e"
float = "#f7768e"
hex = "#f7768e"
integer = "#f7768e"
long = "#f7768e"
octal = "#f7768e"

[comment]
hashbang = "#4e577b"
multiline = "#4e577b"
preproc = "#4e577b"
preprocfile = "#4e577b"
single = "#4e577b"
special = "#4e577b"
